name: CMake Multi-Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-latest, fedora-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Ensure submodules are up-to-date
        run: git submodule update --init --recursive

      - name: Check submodule versions
        run: git submodule status

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          source /etc/os-release
          if [[ "$ID" == "ubuntu" || "$ID_LIKE" == *"debian"* ]]; then
            sudo apt update
            sudo apt install -y cmake g++ make xorg-dev libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          elif [[ "$ID" == "fedora" ]]; then
            sudo dnf builddep SDL3
          else
            echo "Unsupported distribution: $ID"
            exit 1
          fi

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
